# PANDAS TIPS AND TRICKS
written by :Javeria Habib\
email: javriz6@gmail.com


## Make a Dataframe

In [35]:
import pandas as pd

In [36]:
pd.__version__

'2.1.4'

In [37]:
pd.DataFrame({'A col':[1,2,3],'B col':[4,5,6]})

A col  B col
0      1      4
1      2      5
2      3      6

In [38]:
df=pd.DataFrame({'A col':[1,2,3],'B col':[4,5,6]})

### columns must have same values to avoid error

In [39]:
df.head()

A col  B col
0      1      4
1      2      5
2      3      6

In [40]:
df.rename(columns={'A col': 'col_a'}, inplace=True)
print(df)

   col_a  B col
0      1      4
1      2      5
2      3      6


In [41]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### can convert array to dataframe 

In [42]:
pd.DataFrame(arr)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### create random number array

In [43]:
pd.DataFrame(np.random.rand(4,8))

0         1         2         3         4         5         6  \
0  0.195474  0.404250  0.265522  0.611587  0.547066  0.937091  0.051166   
1  0.408533  0.012710  0.011680  0.013989  0.614160  0.927912  0.624545   
2  0.200830  0.573514  0.662397  0.597726  0.241538  0.210316  0.967913   
3  0.796651  0.507070  0.290256  0.396759  0.567675  0.375012  0.709679   

          7  
0  0.511282  
1  0.353314  
2  0.475660  
3  0.852639

In [44]:
pd.DataFrame(np.random.rand(4,8),columns=list
             ('ABCDEFGH'))

A         B         C         D         E         F         G  \
0  0.944244  0.592441  0.729999  0.620848  0.805395  0.957335  0.367788   
1  0.250920  0.161647  0.542690  0.028537  0.360322  0.351358  0.377465   
2  0.768846  0.548157  0.018709  0.759916  0.629840  0.560993  0.259309   
3  0.907297  0.054362  0.177096  0.578536  0.046820  0.635127  0.049661   

          H  
0  0.588392  
1  0.014362  
2  0.016883  
3  0.099915

### Rename columns

In [45]:
df.rename(columns={'A col': 'col_a'}, inplace=True)
print(df)

   col_a  B col
0      1      4
1      2      5
2      3      6


# Using template data

In [46]:
import numpy as np
import seaborn as sns

In [47]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [49]:
df.to_csv('tips_save.csv')
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


In [50]:
from gettext import install



In [51]:

pip install openpyxl

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


### Use Your own data

In [52]:
import pandas as pd
df = pd.read_csv('tips_save.csv')
print(df)

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]
