# PANDAS TIPS AND TRICKS
written by :Javeria Habib\
email: javriz6@gmail.com


## Make a Dataframe

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.1.4'

In [3]:
pd.DataFrame({'A col':[1,2,3],'B col':[4,5,6]})

A col  B col
0      1      4
1      2      5
2      3      6

In [4]:
df=pd.DataFrame({'A col':[1,2,3],'B col':[4,5,6]})

### columns must have same values to avoid error

In [5]:
df.head()

A col  B col
0      1      4
1      2      5
2      3      6

In [6]:
df.rename(columns={'A col': 'col_a'}, inplace=True)
print(df)

   col_a  B col
0      1      4
1      2      5
2      3      6


In [7]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### can convert array to dataframe 

In [8]:
pd.DataFrame(arr)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### create random number array

In [9]:
pd.DataFrame(np.random.rand(4,8))

0         1         2         3         4         5         6  \
0  0.057337  0.821188  0.365623  0.130040  0.154570  0.831675  0.306391   
1  0.887710  0.096254  0.524361  0.430359  0.713222  0.143515  0.615275   
2  0.457236  0.835572  0.843863  0.117075  0.361721  0.854353  0.626050   
3  0.035898  0.556590  0.113828  0.371439  0.148381  0.919280  0.903153   

          7  
0  0.481054  
1  0.899674  
2  0.302603  
3  0.284515

In [10]:
pd.DataFrame(np.random.rand(4,8),columns=list
             ('ABCDEFGH'))

A         B         C         D         E         F         G  \
0  0.058300  0.051250  0.689492  0.992366  0.738347  0.296236  0.065863   
1  0.180538  0.293462  0.635989  0.751876  0.361168  0.530709  0.843886   
2  0.967441  0.384455  0.074880  0.222608  0.867006  0.190300  0.224662   
3  0.111239  0.942471  0.116657  0.822153  0.877405  0.268404  0.137017   

          H  
0  0.878081  
1  0.227447  
2  0.951091  
3  0.889279

### Rename columns

In [11]:
df.rename(columns={'A col': 'col_a'}, inplace=True)
print(df)

   col_a  B col
0      1      4
1      2      5
2      3      6


# Using template data

In [12]:
import numpy as np
import seaborn as sns

In [13]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [15]:
df.to_csv('tips_save.csv')
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


In [28]:
from gettext import install



In [29]:

pip install openpyxl

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


### Use Your own data

In [18]:
import pandas as pd
df = pd.read_csv('tips_save.csv')
print(df)

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]


In [24]:
pip install openpyxl # type: ignore

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
