# PANDAS TIPS AND TRICKS
written by :Javeria Habib\
email: javriz6@gmail.com


## Make a Dataframe

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.1.4'

In [3]:
pd.DataFrame({'A col':[1,2,3],'B col':[4,5,6]})

A col  B col
0      1      4
1      2      5
2      3      6

In [4]:
df=pd.DataFrame({'A col':[1,2,3],'B col':[4,5,6]})

### columns must have same values to avoid error

In [5]:
df.head()

A col  B col
0      1      4
1      2      5
2      3      6

In [6]:
df.rename(columns={'A col': 'col_a'}, inplace=True)
print(df)

   col_a  B col
0      1      4
1      2      5
2      3      6


In [7]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### can convert array to dataframe 

In [8]:
pd.DataFrame(arr)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### create random number array

In [9]:
pd.DataFrame(np.random.rand(4,8))

0         1         2         3         4         5         6  \
0  0.943502  0.407513  0.264837  0.913724  0.154379  0.751611  0.250944   
1  0.278613  0.444707  0.841395  0.934973  0.217317  0.342128  0.240588   
2  0.330715  0.204396  0.487797  0.996400  0.780409  0.330112  0.374215   
3  0.097668  0.898736  0.584943  0.134948  0.614880  0.973243  0.233360   

          7  
0  0.145278  
1  0.172395  
2  0.224339  
3  0.317398

In [10]:
pd.DataFrame(np.random.rand(4,8),columns=list
             ('ABCDEFGH'))

A         B         C         D         E         F         G  \
0  0.291488  0.728620  0.283679  0.715775  0.901103  0.020381  0.008485   
1  0.223751  0.748754  0.316539  0.663690  0.746211  0.715074  0.160256   
2  0.810120  0.480543  0.279917  0.223761  0.144156  0.385177  0.548227   
3  0.094943  0.193108  0.526830  0.793714  0.084590  0.819435  0.108875   

          H  
0  0.020344  
1  0.580363  
2  0.831890  
3  0.071168

### Rename columns

In [11]:
df.rename(columns={'A col': 'col_a'}, inplace=True)
print(df)

   col_a  B col
0      1      4
1      2      5
2      3      6


# Using template data

In [12]:
import numpy as np
import seaborn as sns

In [13]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [15]:
df.to_csv('tips_save.csv')
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


In [16]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
df.to_csv('tips_save.xlsx')
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
